name: 'Publish application'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checkout the code
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0

        # Install .NET Core SDK
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 5.0.x

        # Generate the website
        - name: Publish
          run: dotnet publish Source/SprintName.App/SprintName.App.csproj -c:Release -p:GHPages=true

        # Publish the website
        - name: GitHub Pages action
          if: ${{ github.ref == 'refs/heads/main' }} # Publish only when the push is on master
          uses: peaceiris/actions-gh-pages@v3.6.1
          with:
            github_token: ${{ secrets.PUBLISH_TOKEN }}
            publish_branch: gh-pages
            publish_dir: Source/SprintName.App/bin/Release/net5.0/publish/wwwroot
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
            cname: sprintname.com