name: 'Publish application'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 6.0.100-preview.3.21202.5

        - name: Publish
          run: dotnet publish Source/SprintName.App/SprintName.App.csproj -c Release -r blazor-wasm -p:TrimMode=Link

        - name: GitHub Pages action
          if: ${{ github.ref == 'refs/heads/main' }}
          uses: peaceiris/actions-gh-pages@v3.6.1
          with:
            github_token: ${{ secrets.PUBLISH_TOKEN }}
            publish_branch: gh-pages
            publish_dir: Source/SprintName.App/bin/Release/net5.0/publish/wwwroot
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
            cname: sprintname.com